<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="16.322" timestamp="2023-09-23T12:19:02.159124" hostname="DESKTOP-S15PP4S"><testcase classname="tests.test_employees" name="test_create_employee" time="15.602"><failure message="AssertionError">employees_endpoint = &lt;endpoints.employees.Employees object at 0x0000019CAE42BA90&gt;

    def test_create_employee(employees_endpoint):
&gt;       employees_endpoint.create_employee({
            "name": "Jack",
            "organization": "IT",
            "role": "Junior"
        })

test_employees.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;endpoints.employees.Employees object at 0x0000019CAE42BA90&gt;
data = {'name': 'Jack', 'organization': 'IT', 'role': 'Junior'}

    def create_employee(self, data):
        response = self.session.post(self.url, headers=self.headers, json=data)
        assert response.status_code == 200, f'Actual status code: {response.status_code}'
&gt;       assert response.json() == {
            'employeeId': 2,
            "name": "Jack",
            "organization": "IT",
            "role": "Junior"
        }
E       AssertionError

..\endpoints\employees.py:54: AssertionError</failure></testcase></testsuite></testsuites>